version: '3.1'

services:
  db:
    build: backend/db
    environment:
      POSTGRES_DB: rr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data

